#ifndef __NAV_GRAPHIC_CONTEXT_PLATFORM_PART_HPP__
#define __NAV_GRAPHIC_CONTEXT_PLATFORM_PART_HPP__

#include <Graphic/Nav_Graphic_Context.h>

IMPLEMENT_PLATFORM_PART_UNION(GraphicContext)
{

};
IMPLEMENT_PLATFORM_PART_GET_SIZE(GraphicContext);
IMPLEMENT_GET_PLATFORM_PART(GraphicContext);

#endif